<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Account_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aq2emp_account by id
     */
    function get_aq2emp_account($id)
    {
        return $this->db->get_where('aq2emp_accounts',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all aq2emp_accounts
     */
    function get_all_aq2emp_accounts()
    {
        return $this->db->get('aq2emp_accounts')->result_array();
    }
    
    /*
     * function to add new aq2emp_account
     */
    function add_aq2emp_account($params)
    {
        $this->db->insert('aq2emp_accounts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aq2emp_account
     */
    function update_aq2emp_account($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_accounts',$params);
        if($response)
        {
            return "aq2emp_account updated successfully";
        }
        else
        {
            return "Error occuring while updating aq2emp_account";
        }
    }
    
    /*
     * function to delete aq2emp_account
     */
    function delete_aq2emp_account($id)
    {
        $response = $this->db->delete('aq2emp_accounts',array('id'=>$id));
        if($response)
        {
            return "aq2emp_account deleted successfully";
        }
        else
        {
            return "Error occuring while deleting aq2emp_account";
        }
    }
}
