<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class CampaignFormPage_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campaign_forms_page by id
     */
    function get_campaign_form_page($id)
    {
        return $this->db->get_where('aq2emp_campaign_forms_page',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all campaign_forms_page
     */
    function get_all_campaign_form_pages()
    {
        return $this->db->get('aq2emp_campaign_forms_page')->result_array();
    }
    
    /*
     *
     
		SELECT cfp.[id]
		      ,cfp.[campaign_id]
		      ,cfp.[form_id]
		      ,cfp.[main_bg]
		      ,cfp.[main_header]
		      ,cfp.[main_sub_header]
		      ,cfp.[main_sub_sub_header]
		      ,cfp.[top_image]
		      ,cf.[form_title]
		      ,cf.[form_sub_text]
		      ,cf.[form_image]
		  FROM [aq2e_marketing_platforrm].[dbo].[aq2emp_campaign_forms_page_page] cfp
		   INNER JOIN [aq2e_marketing_platforrm].[dbo].[aq2emp_campaign_forms_page] cf ON cf.id = cfp.form_id
		   WHERE cfp.[id] = 12362
		
		  SELECT cff.[name]
		      ,cff.[order]
		      ,cff.[type]
		      ,cff.[required]
		  FROM [aq2e_marketing_platforrm].[dbo].[aq2emp_campaign_forms_page_fields] cff
		  WHERE cff.form_id = 1
     *
     */
    
    /*
     * function to add new aq2emp_campaign_forms_page
     */
    function add_campaign_form_page($params)
    {
        $this->db->insert('aq2emp_campaign_forms_page',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update campaign_forms_page
     */
    function update_campaign_form_page($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_campaign_forms_page',$params);
        if($response)
        {
            return "campaign_forms_page updated successfully";
        }
        else
        {
            return "Error occuring while updating campaign_forms_page";
        }
    }
    
    /*
     * function to delete campaign_forms_page
     */
    function delete_campaign_form_page($id)
    {
        $response = $this->db->delete('aq2emp_campaign_forms_page',array('id'=>$id));
        if($response)
        {
            return "campaign_forms_page deleted successfully";
        }
        else
        {
            return "Error occuring while deleting campaign_forms_page";
        }
    }
}
