<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class CampaignFormField_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campaign_form_field by id
     */
    function get_campaign_form_field($id)
    {
        return $this->db->get_where('aq2emp_campaign_form_fields',array('id'=>$id))->row_array();
    }
	
	/*
     * Get campaign_form_fields by id
     */
	function get_campaign_form_fields( $form_id )
	{
		return $this->db->get_where('aq2emp_campaign_form_fields',array('form_id'=> intval( $form_id ) ))->result_array();
	}
    
    /*
     * Get all campaign_form_fields
     */
    function get_all_campaign_form_fields()
    {
        return $this->db->get('aq2emp_campaign_form_fields')
	                    ->order_by( 'order', 'ASC' )
                        ->result_array();
    }
    
    /*
     *
     
		SELECT cfp.[id]
		      ,cfp.[campaign_id]
		      ,cfp.[form_id]
		      ,cfp.[main_bg]
		      ,cfp.[main_header]
		      ,cfp.[main_sub_header]
		      ,cfp.[main_sub_sub_header]
		      ,cfp.[top_image]
		      ,cf.[form_title]
		      ,cf.[form_sub_text]
		      ,cf.[form_image]
		  FROM [aq2e_marketing_platforrm].[dbo].[aq2emp_campaign_forms_page] cfp
		   INNER JOIN [aq2e_marketing_platforrm].[dbo].[aq2emp_campaign_forms] cf ON cf.id = cfp.form_id
		   WHERE cfp.[id] = 12362
		
		  SELECT cff.[name]
		      ,cff.[order]
		      ,cff.[type]
		      ,cff.[required]
		  FROM [aq2e_marketing_platforrm].[dbo].[aq2emp_campaign_form_fields] cff
		  WHERE cff.form_id = 1
     *
     */
    
    /*
     * function to add new campaign_form_field
     */
    function add_campaign_form_field($params)
    {
        $this->db->insert('aq2emp_campaign_form_fields',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update campaign_form_fields
     */
    function update_campaign_form_field($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_campaign_form_fields',$params);
        if($response)
        {
            return "aq2emp_campaign_form updated successfully";
        }
        else
        {
            return "Error occuring while updating aq2emp_campaign_form";
        }
    }
    
    /*
     * function to delete campaign_form_field
     */
    function delete_campaign_form_field($id)
    {
        $response = $this->db->delete('aq2emp_campaign_form_fields',array('id'=>$id));
        if($response)
        {
            return "aq2emp_campaign_form_fields deleted successfully";
        }
        else
        {
            return "Error occuring while deleting aq2emp_campaign_form_fields";
        }
    }
}
