<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Campaign_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campaign by id
     */
    function get_campaign($id)
    {
        return $this->db->get_where('aq2emp_campaigns',array('id'=>intval($id)))->row_array();
    }

    /*
     * Get all campaigns
     */
    function get_all_campaigns()
    {
        return $this->db->get('aq2emp_campaigns')->result_array();
    }

    /*
     * function to add new campaign
     */
    function add_campaign($params)
    {
        $this->db->insert('aq2emp_campaigns',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update campaign
     */
    function update_campaign($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_campaigns',$params);
        if($response)
        {
            return "campaign updated successfully";
        }
        else
        {
            return "Error occuring while updating campaign";
        }
    }

    /*
     * function to delete campaign
     */
    function delete_campaign($id)
    {
        $response = $this->db->delete('aq2emp_campaigns',array('id'=>$id));
        if($response)
        {
            return "campaign deleted successfully";
        }
        else
        {
            return "Error occuring while deleting campaign";
        }
    }
}
