<?php

/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class CampaignExternalAPIForm_model extends ResourceModel {
	
    function __construct() {
        parent::__construct();
    }
    
    /*
     * Get campaign_capture_links by id
     */
    function get_campaign_external_api_form($id) {
	
	    $res = $this->db->select('
                api.campaign_id
			  , api.external_form_id')
	                          ->from('aq2emp_campaigns_external_api_forms api')
	                          ->where( array( 'api.campaign_id' => intval($id) ) )
	                          ->get();
	
	    return $res->result_array();
    }
    
    /*
     * Get all campaign_capture_links
     */
    function get_all_campaign_external_api_forms() {
        return $this->db->get('aq2emp_campaigns_external_api_forms')->result_array();
    }
    
    /*
     * function to add new aq2emp_campaign_capture_link
     */
    function add_campaign_capture_link($params)
    {
        $this->db->insert('aq2emp_campaigns_external_api_forms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update campaign_forms_page
     */
    function update_campaign_external_api_form($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_campaigns_external_api_forms',$params);
        if($response)
        {
            return "campaigns_external_api_forms updated successfully";
        }
        else
        {
            return "Error occurring while updating campaigns_external_api_forms";
        }
    }
    
    /*
     * function to delete campaign_capture_link
     */
    function delete_campaign_external_api_form($id)
    {
        $response = $this->db->delete('aq2emp_campaigns_external_api_forms',array('id'=>$id));
        if($response)
        {
            return "campaigns_external_api_forms deleted successfully";
        }
        else
        {
            return "Error occurring while deleting campaigns_external_api_forms";
        }
    }
}
