<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event by id
     */
    function get_event($id)
    {
        return $this->db->get_where('aq2emp_defined_events',array('id'=>intval($id)))->row_array();
    }
    
    /*
     * Get all events
     */
    function get_all_events()
    {
        return $this->db->get('aq2emp_defined_events')->result_array();
    }
    
    /*
     * function to add new event
     */
    function add_event($params)
    {
        $this->db->insert('aq2emp_defined_events',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event
     */
    function update_event($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_defined_events',$params);
        if($response)
        {
            return "event updated successfully";
        }
        else
        {
            return "Error occuring while updating event";
        }
    }
    
    /*
     * function to delete event
     */
    function delete_event($id)
    {
        $response = $this->db->delete('aq2emp_defined_events',array('id'=>$id));
        if($response)
        {
            return "event deleted successfully";
        }
        else
        {
            return "Error occuring while deleting event";
        }
    }
}
