<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class MarketingPreferences_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campaign by id
     */
    function get_marketing_preference($id)
    {
        return $this->db->get_where('aq2emp_account_preferences',array('id'=>intval($id)))->row_array();
    }

    /*
     * Get all campaigns
     */
    function get_all_marketing_preferences()
    {
        return $this->db->get('aq2emp_account_preferences')->result_array();
    }

    /*
     * function to add new campaign
     */

    function add_marketing_preference($params)
    {
        $this->db->insert('aq2emp_account_preferences',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update campaign
     */
    function update_marketing_preference($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('aq2emp_account_preferences',$params);
        if($response)
        {
            return "campaign updated successfully";
        }
        else
        {
            return "Error occuring while updating campaign";
        }
    }

    /*
     * function to delete campaign
     */
    function delete_marketing_preference($id)
    {
        $response = $this->db->delete('aq2emp_account_preferences',array('id'=>$id));
        if($response)
        {
            return "marketing_preference deleted successfully";
        }
        else
        {
            return "Error occuring while deleting marketing_preference";
        }
    }
}
