<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Subscriber_model extends ResourceModel
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aq2emp_subscriber by id
     */
    function get_subscriber($id)
    {
        return $this->db->get_where('aq2emp_subscribers',array('id'=>$id))->row_array();
    }
	
	function get_subscriber_by_subscriber_id( $subscriber_id )
	{
		return $this->db->get_where('aq2emp_subscribers', array( 'subscriber_id'=> $subscriber_id ) )->row_array();
	}
	
	function get_subscriber_by_email( $email )
	{
		return $this->db->get_where('aq2emp_subscribers', array( 'email'=>$email ) )->row_array();
	}
    
    /*
     * Get all aq2emp_subscribers
     */
    function get_all_subscribers()
    {
        return $this->db->get('aq2emp_subscribers')->result_array();
    }
    
    /*
     * function to add new aq2emp_subscriber
     */
	
    function add_subscriber( $params ) {
		    $this->db->insert( 'aq2emp_subscribers', $params );
		    return $this->db->insert_id();
    }
    
    /*
     * function to update aq2emp_subscriber
     */
    function update_subscriber($subscriber_id, $params)
    {
        $this->db->where( 'subscriber_id', $subscriber_id );
        
        $response = $this->db->update('aq2emp_subscribers', $params);
        
        if($response)
        {
            return "aq2emp_subscriber updated successfully";
        }
        else
        {
            return "Error occurring while updating aq2emp_subscriber";
        }
        
    }
    
    /*
     * function to delete aq2emp_subscriber
     */
    function delete_aq2emp_subscriber($id)
    {
        $response = $this->db->delete('aq2emp_subscribers',array('id'=>$id));
        if($response)
        {
            return "aq2emp_subscriber deleted successfully";
        }
        else
        {
            return "Error occuring while deleting aq2emp_subscriber";
        }
    }
}
